/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.ecat.ws;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface NubLookup {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"NubLookup\",\"namespace\":\"org.gbif.ecat.ws\",\"types\":[{\"type\":\"record\",\"name\":\"Request\",\"fields\":[{\"name\":\"kingdom\",\"type\":[\"string\",\"null\"]},{\"name\":\"phylum\",\"type\":[\"string\",\"null\"]},{\"name\":\"class\",\"type\":[\"string\",\"null\"]},{\"name\":\"order\",\"type\":[\"string\",\"null\"]},{\"name\":\"family\",\"type\":[\"string\",\"null\"]},{\"name\":\"genus\",\"type\":[\"string\",\"null\"]},{\"name\":\"name\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"record\",\"name\":\"Response\",\"fields\":[{\"name\":\"kingdomId\",\"type\":[\"int\",\"null\"]},{\"name\":\"phylumId\",\"type\":[\"int\",\"null\"]},{\"name\":\"classId\",\"type\":[\"int\",\"null\"]},{\"name\":\"orderId\",\"type\":[\"int\",\"null\"]},{\"name\":\"familyId\",\"type\":[\"int\",\"null\"]},{\"name\":\"genusId\",\"type\":[\"int\",\"null\"]},{\"name\":\"nameId\",\"type\":[\"int\",\"null\"]}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"request\",\"type\":\"Request\"}],\"response\":\"Response\"}}}");
  org.gbif.ecat.ws.Response send(org.gbif.ecat.ws.Request request) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends NubLookup {
    public static final org.apache.avro.Protocol PROTOCOL = org.gbif.ecat.ws.NubLookup.PROTOCOL;
    void send(org.gbif.ecat.ws.Request request, org.apache.avro.ipc.Callback<org.gbif.ecat.ws.Response> callback) throws java.io.IOException;
  }
}